name: WapUniverse
version: 0.0.1
description: WapUniverse Map Editor
author: cubuspl42

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  stagexl: '^0.12.0+1'

transformers:
